
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox3;

	private global::Gtk.VBox vbox4;

	private global::Gtk.Label label3;

	private global::Gtk.Entry Pantalla;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button BVaciar;

	private global::Gtk.Button BC;

	private global::Gtk.VBox vbox5;

	private global::Gtk.HBox hbox10;

	private global::Gtk.Button BSiete;

	private global::Gtk.Button BOcho;

	private global::Gtk.Button BNueve;

	private global::Gtk.Button BCociente;

	private global::Gtk.HBox hbox11;

	private global::Gtk.Button BCuatro;

	private global::Gtk.Button BCinco;

	private global::Gtk.Button BSeis;

	private global::Gtk.Button BProducto;

	private global::Gtk.HBox hbox12;

	private global::Gtk.Button BUno;

	private global::Gtk.Button BDos;

	private global::Gtk.Button BTres;

	private global::Gtk.Button BResta;

	private global::Gtk.VBox vbox6;

	private global::Gtk.HBox hbox13;

	private global::Gtk.Button button14;

	private global::Gtk.Button BCero;

	private global::Gtk.Button BIgual;

	private global::Gtk.Button BSuma;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("CALCULADORA");
		this.vbox4.Add(this.label3);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label3]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.Pantalla = new global::Gtk.Entry();
		this.Pantalla.CanFocus = true;
		this.Pantalla.Name = "Pantalla";
		this.Pantalla.IsEditable = false;
		this.Pantalla.InvisibleChar = '•';
		this.vbox4.Add(this.Pantalla);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.Pantalla]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.BVaciar = new global::Gtk.Button();
		this.BVaciar.WidthRequest = 120;
		this.BVaciar.CanFocus = true;
		this.BVaciar.Name = "BVaciar";
		this.BVaciar.UseUnderline = true;
		this.BVaciar.Label = global::Mono.Unix.Catalog.GetString("VACIAR");
		this.hbox1.Add(this.BVaciar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.BVaciar]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.BC = new global::Gtk.Button();
		this.BC.WidthRequest = 50;
		this.BC.CanFocus = true;
		this.BC.Name = "BC";
		this.BC.UseUnderline = true;
		this.BC.Label = global::Mono.Unix.Catalog.GetString("C");
		this.hbox1.Add(this.BC);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.BC]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox4.Add(this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox1]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox3.Add(this.vbox4);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox4]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 51;
		// Container child hbox10.Gtk.Box+BoxChild
		this.BSiete = new global::Gtk.Button();
		this.BSiete.WidthRequest = 55;
		this.BSiete.HeightRequest = 28;
		this.BSiete.CanFocus = true;
		this.BSiete.Name = "BSiete";
		this.BSiete.UseUnderline = true;
		this.BSiete.Label = global::Mono.Unix.Catalog.GetString("7");
		this.hbox10.Add(this.BSiete);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.BSiete]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.BOcho = new global::Gtk.Button();
		this.BOcho.WidthRequest = 55;
		this.BOcho.CanFocus = true;
		this.BOcho.Name = "BOcho";
		this.BOcho.UseUnderline = true;
		this.BOcho.Label = global::Mono.Unix.Catalog.GetString("8");
		this.hbox10.Add(this.BOcho);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.BOcho]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.BNueve = new global::Gtk.Button();
		this.BNueve.WidthRequest = 55;
		this.BNueve.CanFocus = true;
		this.BNueve.Name = "BNueve";
		this.BNueve.UseUnderline = true;
		this.BNueve.Label = global::Mono.Unix.Catalog.GetString("9");
		this.hbox10.Add(this.BNueve);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.BNueve]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.BCociente = new global::Gtk.Button();
		this.BCociente.WidthRequest = 50;
		this.BCociente.CanFocus = true;
		this.BCociente.Name = "BCociente";
		this.BCociente.UseUnderline = true;
		this.BCociente.Label = global::Mono.Unix.Catalog.GetString("/");
		this.hbox10.Add(this.BCociente);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.BCociente]));
		w10.Position = 3;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox5.Add(this.hbox10);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox10]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 51;
		// Container child hbox11.Gtk.Box+BoxChild
		this.BCuatro = new global::Gtk.Button();
		this.BCuatro.WidthRequest = 55;
		this.BCuatro.CanFocus = true;
		this.BCuatro.Name = "BCuatro";
		this.BCuatro.UseUnderline = true;
		this.BCuatro.Label = global::Mono.Unix.Catalog.GetString("4");
		this.hbox11.Add(this.BCuatro);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.BCuatro]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.BCinco = new global::Gtk.Button();
		this.BCinco.WidthRequest = 55;
		this.BCinco.CanFocus = true;
		this.BCinco.Name = "BCinco";
		this.BCinco.UseUnderline = true;
		this.BCinco.Label = global::Mono.Unix.Catalog.GetString("5");
		this.hbox11.Add(this.BCinco);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.BCinco]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.BSeis = new global::Gtk.Button();
		this.BSeis.WidthRequest = 55;
		this.BSeis.CanFocus = true;
		this.BSeis.Name = "BSeis";
		this.BSeis.UseUnderline = true;
		this.BSeis.Label = global::Mono.Unix.Catalog.GetString("6");
		this.hbox11.Add(this.BSeis);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.BSeis]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.BProducto = new global::Gtk.Button();
		this.BProducto.WidthRequest = 50;
		this.BProducto.CanFocus = true;
		this.BProducto.Name = "BProducto";
		this.BProducto.UseUnderline = true;
		this.BProducto.Label = global::Mono.Unix.Catalog.GetString("x");
		this.hbox11.Add(this.BProducto);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.BProducto]));
		w15.Position = 3;
		w15.Expand = false;
		w15.Fill = false;
		this.vbox5.Add(this.hbox11);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox11]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 51;
		// Container child hbox12.Gtk.Box+BoxChild
		this.BUno = new global::Gtk.Button();
		this.BUno.WidthRequest = 55;
		this.BUno.CanFocus = true;
		this.BUno.Name = "BUno";
		this.BUno.UseUnderline = true;
		this.BUno.Label = global::Mono.Unix.Catalog.GetString("1");
		this.hbox12.Add(this.BUno);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.BUno]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.BDos = new global::Gtk.Button();
		this.BDos.WidthRequest = 55;
		this.BDos.CanFocus = true;
		this.BDos.Name = "BDos";
		this.BDos.UseUnderline = true;
		this.BDos.Label = global::Mono.Unix.Catalog.GetString("2");
		this.hbox12.Add(this.BDos);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.BDos]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.BTres = new global::Gtk.Button();
		this.BTres.WidthRequest = 55;
		this.BTres.CanFocus = true;
		this.BTres.Name = "BTres";
		this.BTres.UseUnderline = true;
		this.BTres.Label = global::Mono.Unix.Catalog.GetString("3");
		this.hbox12.Add(this.BTres);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.BTres]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.BResta = new global::Gtk.Button();
		this.BResta.WidthRequest = 50;
		this.BResta.CanFocus = true;
		this.BResta.Name = "BResta";
		this.BResta.UseUnderline = true;
		this.BResta.Label = global::Mono.Unix.Catalog.GetString("-");
		this.hbox12.Add(this.BResta);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.BResta]));
		w20.Position = 3;
		w20.Expand = false;
		w20.Fill = false;
		this.vbox5.Add(this.hbox12);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox12]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		this.vbox3.Add(this.vbox5);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox5]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 53;
		// Container child hbox13.Gtk.Box+BoxChild
		this.button14 = new global::Gtk.Button();
		this.button14.WidthRequest = 50;
		this.button14.CanFocus = true;
		this.button14.Name = "button14";
		this.button14.UseUnderline = true;
		this.button14.Label = global::Mono.Unix.Catalog.GetString(",");
		this.hbox13.Add(this.button14);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.button14]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.BCero = new global::Gtk.Button();
		this.BCero.WidthRequest = 55;
		this.BCero.CanFocus = true;
		this.BCero.Name = "BCero";
		this.BCero.UseUnderline = true;
		this.BCero.Label = global::Mono.Unix.Catalog.GetString("0");
		this.hbox13.Add(this.BCero);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.BCero]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.BIgual = new global::Gtk.Button();
		this.BIgual.WidthRequest = 55;
		this.BIgual.CanFocus = true;
		this.BIgual.Name = "BIgual";
		this.BIgual.UseUnderline = true;
		this.BIgual.Label = global::Mono.Unix.Catalog.GetString("=");
		this.hbox13.Add(this.BIgual);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.BIgual]));
		w25.Position = 2;
		w25.Expand = false;
		w25.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.BSuma = new global::Gtk.Button();
		this.BSuma.WidthRequest = 55;
		this.BSuma.CanFocus = true;
		this.BSuma.Name = "BSuma";
		this.BSuma.UseUnderline = true;
		this.BSuma.Label = global::Mono.Unix.Catalog.GetString("+");
		this.hbox13.Add(this.BSuma);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.BSuma]));
		w26.Position = 3;
		w26.Expand = false;
		w26.Fill = false;
		this.vbox6.Add(this.hbox13);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox13]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		this.vbox3.Add(this.vbox6);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox6]));
		w28.Position = 2;
		w28.Expand = false;
		w28.Fill = false;
		this.Add(this.vbox3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 374;
		this.DefaultHeight = 448;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.BVaciar.Clicked += new global::System.EventHandler(this.OnBVaciarClicked);
		this.BC.Clicked += new global::System.EventHandler(this.OnBCClicked);
		this.BSiete.Clicked += new global::System.EventHandler(this.OnBSieteClicked);
		this.BOcho.Clicked += new global::System.EventHandler(this.OnBOchoClicked);
		this.BNueve.Clicked += new global::System.EventHandler(this.OnBNueveClicked);
		this.BCociente.Clicked += new global::System.EventHandler(this.OnBCocienteClicked);
		this.BCuatro.Clicked += new global::System.EventHandler(this.OnBCuatroClicked);
		this.BCinco.Clicked += new global::System.EventHandler(this.OnBCincoClicked);
		this.BSeis.Clicked += new global::System.EventHandler(this.OnBSeisClicked);
		this.BProducto.Clicked += new global::System.EventHandler(this.OnBProductoClicked);
		this.BUno.Clicked += new global::System.EventHandler(this.OnBUnoClicked);
		this.BDos.Clicked += new global::System.EventHandler(this.OnBDosClicked);
		this.BTres.Clicked += new global::System.EventHandler(this.OnBTresClicked);
		this.BResta.Clicked += new global::System.EventHandler(this.OnBRestaClicked);
		this.button14.Clicked += new global::System.EventHandler(this.OnButton14Clicked);
		this.BCero.Clicked += new global::System.EventHandler(this.OnBCeroClicked);
		this.BSuma.Clicked += new global::System.EventHandler(this.OnBSumaClicked);
	}
}
